setting up Pay class and reformatting file structure
rwldng/NewBank pull request #3
Opened 2021-03-31 01:45 UTC by abuadu

Setting up Pay class, adding default account functionality and reformatting file structure as discussed on Discord

2021-04-02 23:18 UTC, HajaRand commented on newbank/server/Customer.java
> +		return accounts.get(0);
Check for if accounts have anything before returning the [0]th `Account`

2021-04-02 23:36 UTC, HajaRand requested changes

2021-04-02 23:36 UTC, HajaRand commented on newbank/server/NewBank.java
> +			case "PAY" :
`PAY`, `SHOWMYACCOUNTS`, `SUCCESS` and `FAIL` should be in enums and imported into this class.

2021-04-02 23:36 UTC, HajaRand commented on newbank/server/Pay.java
> +    public boolean makePayment(Account sender, double paymentAmount, String recipient) {
`String recipient` does not seems to be used in the below method. Please remove if not required.

2021-04-02 23:36 UTC, HajaRand commented on newbank/server/Pay.java
> +            return false;
Can we capture this exception instead of `return false`?

2021-04-04 03:26 UTC, abuadu commented on newbank/server/NewBank.java
> +			case "PAY" :
I added enums for the Actions but I'm not sure if we need an enum for SUCCESS or FAIL because it seems to me that they're just meant to be strings. Let me know your thoughts!

2021-04-04 21:51 UTC, HajaRand approved these changes

2021-04-06 00:23 UTC, merged